env:
  browser: true
  es2022: true
  node: true
  mocha: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
plugins:
  - react
rules:
  indent: 0
  curly:
    - 2
    - all
  lines-around-comment:
    - 2
    - beforeBlockComment: true
      afterBlockComment: true
      beforeLineComment: true
      afterLineComment: true
      allowBlockStart: true
      allowBlockEnd: true
      allowObjectStart: true
      allowObjectEnd: true
      allowArrayStart: true
      allowArrayEnd: true
  max-len: 0
  no-confusing-arrow: 0
  no-mixed-operators: 2
  no-tabs:
    - 2
    - allowIndentationTabs: true
  no-unexpected-multiline: 2
  quotes:
    - 2
    - single
    - avoidEscape: true
      allowTemplateLiterals: false
  no-restricted-syntax: 0
  import/no-extraneous-dependencies: 0
  import/no-dynamic-require: 0
  global-require: 0
  import/no-unresolved: 0
  react/react-in-jsx-scope: 0
  default-param-last: 0
  react/prop-types: 0
  no-plusplus: 0
  jsx-a11y/label-has-associated-control:
    - 2
    - labelComponents: [CustomInputLabel]
      labelAttributes: [label]
      controlComponents: [CustomInput]
      depth: 3
  jsx-a11y/control-has-associated-label: 0
  no-alert: 0
  array-callback-return: 0
  consistent-return: 0
ignorePatterns: ['node_modules/', 'dist/']
